### ISSUE TITLE
cubied doesn't reap zombies

### ISSUE THREAD

**Issue by ponyisi** [hepsw/cubie#2]
Hi Sebastien,

When trying to use cubied to manage a container used for running a batch system worker node, I find that I get a huge number of zombie processes.  This seems to be because cubied, as PID 1, isn't  reaping orphaned processes.  It's a bit of a problem for a long-running container.

Best,
Peter

**Comment by sbinet** [comment]
it is, indeed, an issue.
are the orphaned processes originating from the "master" command or from the extra "daemon-like" commands?

**Comment by ponyisi** [comment]
They're at least originating from the initial processes (those described in the cubie.d configuration files).  For example, I start Condor daemons (running condor_master) and after every job I have lingering condor_starter and sh processes.  I'm not sure whether they result from the "final" processes.

**Comment by sbinet** [comment]
I believe I fixed it (aplogies it took so long)
feel free to re-open if you disagree :)

(I am in the process of updating the `hepsw/docks` containers)
