### ISSUE TITLE
Shell not found

### ISSUE THREAD

**Issue by kreczko** [hepsw/cubie#3]
When running one of the CVMFS containers in a gitlab pipeline, I am getting the following output.
```bash
2017/09/05 12:42:16 running [sh -c if [ -x /usr/local/bin/bash ]; then
	exec /usr/local/bin/bash 
elif [ -x /usr/bin/bash ]; then
	exec /usr/bin/bash 
elif [ -x /bin/bash ]; then
	exec /bin/bash 
elif [ -x /usr/local/bin/sh ]; then
	exec /usr/local/bin/sh 
elif [ -x /usr/bin/sh ]; then
	exec /usr/bin/sh 
elif [ -x /bin/sh ]; then
	exec /bin/sh 
else
	echo shell not found
	exit 1
fi

]...
```
Since this looks identical to the `PATH` variable minus `sbin` (`/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`), I was wondering if this has something to do with cubie or not.

For the container I have both
```docker
ENTRYPOINT ["/usr/bin/cubied"]
CMD ["bash"]
```

Please let me know what additional information you require.

**Comment by kreczko** [comment]
Apologies, after further investigation, this seems like it is a problem with the gitlab-runner.

**Comment by sbinet** [comment]
glad you resolved it :)

out of curiosity, what was the issue with the gitlab-runner?

**Comment by kreczko** [comment]
The issue is the non-standard shell:
https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/issues/1169
https://gitlab.com/gitlab-org/gitlab-ci-multi-runner/issues/1550

Basically the `ENTRYPOINT ["/usr/bin/cubied"]` confuses the runner and it spews these harmless, but cluttering messages.

BTW: I posted by solution in hepsw/docks, you've already found it :).
